# Generated by Django 3.1 on 2020-11-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivity', models.FloatField()),
                ('negativity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DaySentimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conservative_sentiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conservative', to='AIDataModeler.sentimentmodel')),
                ('liberal_sentiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liberal', to='AIDataModeler.sentimentmodel')),
                ('overall_sentiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='overall', to='AIDataModeler.sentimentmodel')),
            ],
        ),
    ]
