# Generated by Django 3.1 on 2020-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daysentimentdata',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='daysentimentdata',
            name='title',
            field=models.CharField(default='null', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
