# Generated by Django 3.1 on 2020-11-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0003_remove_daysentimentdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysentimentdata',
            name='date_str',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
