# Generated by Django 3.1 on 2020-12-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0004_daysentimentdata_date_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysentimentdata',
            name='word_map',
            field=models.FilePathField(default='', path='/img'),
            preserve_default=False,
        ),
    ]
