# Generated by Django 3.1 on 2020-12-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0005_daysentimentdata_word_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysentimentdata',
            name='word_map',
        ),
    ]
