# Generated by Django 3.1 on 2020-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0006_remove_daysentimentdata_word_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysentimentdata',
            name='word_map_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
