# Generated by Django 3.1 on 2020-12-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0007_daysentimentdata_word_map_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnn', models.FloatField()),
                ('politico', models.FloatField()),
                ('usa_today', models.FloatField()),
                ('upi', models.FloatField()),
                ('federalist', models.FloatField()),
                ('average', models.FloatField()),
                ('average_consevative', models.FloatField()),
                ('average_liberal', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='daysentimentdata',
            name='conservative_sentiment',
        ),
        migrations.RemoveField(
            model_name='daysentimentdata',
            name='liberal_sentiment',
        ),
        migrations.RemoveField(
            model_name='daysentimentdata',
            name='overall_sentiment',
        ),
        migrations.DeleteModel(
            name='SentimentModel',
        ),
        migrations.AddField(
            model_name='daysentimentdata',
            name='outlet_sentiment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sentiment', to='AIDataModeler.outletsentiment'),
            preserve_default=False,
        ),
    ]
