# Generated by Django 3.1 on 2020-12-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0008_auto_20201206_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysentimentdata',
            name='outlet_sentiment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sentiment', to='AIDataModeler.outletsentiment'),
        ),
    ]
