# Generated by Django 3.1 on 2020-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIDataModeler', '0010_auto_20201206_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsentiment',
            name='unique_key_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
